// Generated by scripts/build-bgm.py; do not edit by hand.
export const BGM_LOOP = {
  /** Length of audio/boot-intro.ogg: the reference boot sound before the music starts. */
  introSeconds: 15.88,
  /** Seconds of the recording's music skipped before the loop file starts. */
  musicOffset: 6.68,
  /** audio/bgm-loop.ogg plays from 0 once, then repeats [loopStart, loopEnd). */
  loopStart: 81.32075,
  loopEnd: 160.663167,
  duration: 160.663167,
} as const;
